name: Build And Release
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
jobs:
    build-release:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/araxiaonline/ac-wotlk-worldserver-devcontainer:latest
            options: --user root
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: build
              uses: araxiaonline/share-gh-workflows/.github/actions/build-tag-release@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                tag_release: true
                event_name: ${{ github.event_name }}

