name: core-build
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'eyeofstorm/azerothcore-wotlk'
          ref: 'mod-npc-bots-hooks'
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: 'modules/mod-npc-bots'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.ccache
          key: ccache:${{ matrix.compiler }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.compiler }}:${{ github.ref }}
            ccache:${{ matrix.compiler }}
      - name: Configure OS
        run: source ./apps/ci/ci-install.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Build
        run: source ./apps/ci/ci-compile.sh
