#ifndef MOD_OLLAMA_CHAT_PERSONALITY_H
#define MOD_OLLAMA_CHAT_PERSONALITY_H

#include <unordered_map>
#include <string>
#include <cstdint>

class Player; // forward declaration

enum BotPersonalityType {
    PERSONALITY_GAMER,
    PERSONALITY_ROLEPLAYER,
    PERSONALITY_LOOTGOBLIN,
    PERSONALITY_PVP_HARDCORE,
    PERSONALITY_RAIDER,
    PERSONALITY_CASUAL,
    PERSONALITY_TRADER,
    PERSONALITY_NPC_IMPERSONATOR,
    PERSONALITY_GRUMPY_VETERAN,
    PERSONALITY_HEROIC_LEADER,
    PERSONALITY_TRICKSTER,
    PERSONALITY_LONE_WOLF,
    PERSONALITY_FOOL,
    PERSONALITY_ANCIENT_WISE_ONE,
    PERSONALITY_BARD,
    PERSONALITY_CONSPIRACY_THEORIST,
    PERSONALITY_EDGE_LORD,
    PERSONALITY_FANATIC,
    PERSONALITY_HYPE_MAN,
    PERSONALITY_PARANOID,
    PERSONALITY_FLIRT,
    PERSONALITY_RAGER,
    PERSONALITY_STONER,
    PERSONALITY_YOUNG_APPRENTICE,
    PERSONALITY_MENTOR,
    PERSONALITY_SCHOLAR,
    PERSONALITY_GLITCHED_AI,
    PERSONALITY_WANNABE_VILLAIN,
    PERSONALITY_JOLLY_BEER_LOVER,
    PERSONALITY_GOBLIN_MERCHANT,
    PERSONALITY_PIRATE,
    PERSONALITY_CHEF,
    PERSONALITY_POET,
    PERSONALITY_TYPES_COUNT
};

BotPersonalityType GetBotPersonality(Player* bot);
std::string GetPersonalityPromptAddition(BotPersonalityType type);

#endif // MOD_OLLAMA_CHAT_PERSONALITY_H
